# Generated by Django 5.2 on 2025-04-09 02:26

import bwf_core.models
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('version_number', models.IntegerField(default=1)),
                ('workflow_file', models.FileField(blank=True, max_length=1000, null=True, storage=django.core.files.storage.FileSystemStorage(location='/data/data/projects/spatial-layer-monitor/private-media'), upload_to=bwf_core.models.upload_to_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variables', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'initial'), ('RUNNING', 'running'), ('COMPLETED', 'completed'), ('ERROR', 'error')], default='PENDING', max_length=50)),
                ('error_message', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=100)),
                ('component_definition', models.JSONField(blank=True, null=True)),
                ('plugin_id', models.CharField(blank=True, max_length=500, null=True)),
                ('plugin_version', models.CharField(blank=True, max_length=15, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('input', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'initial'), ('RUNNING', 'running'), ('COMPLETED', 'completed'), ('AWAITING_ACTION', 'awaiting_action'), ('ERROR', 'error'), ('TERMINATED', 'terminated')], default='PENDING', max_length=50)),
                ('error_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_nodes', to='bwf_core.componentinstance')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_actions', to='bwf_core.workflowinstance')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'success'), ('ERROR', 'error'), ('PENDING', 'pending'), ('STARTED', 'started'), ('STOPPED', 'stopped'), ('RESTARTED', 'restarted'), ('TERMINATED', 'terminated')], default='STARTED', max_length=100)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='bwf_core.componentinstance')),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='bwf_core.workflowinstance')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=15)),
                ('version_name', models.CharField(max_length=50)),
                ('applied_on', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edition', models.BooleanField(default=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_file', models.FileField(blank=True, max_length=1000, null=True, storage=django.core.files.storage.FileSystemStorage(location='/data/data/projects/spatial-layer-monitor/private-media'), upload_to=bwf_core.models.updaload_to_workflow_edition_path)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_versions', to='bwf_core.workflowversion')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bwf_core.workflow')),
            ],
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='workflow_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='bwf_core.workflowversion'),
        ),
    ]
