# Generated by Django 5.2 on 2025-05-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwf_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='worflow_type',
            field=models.CharField(choices=[('LONG_LIVED', 'Long Lived'), ('SHORT_LIVED', 'Short Lived')], default='SHORT_LIVED', max_length=50),
        ),
    ]
