# Generated by Django 5.2 on 2025-05-20 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bwf_core', '0002_workflow_worflow_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='worflow_type',
            new_name='workflow_type',
        ),
    ]
