# Generated by Django 5.2 on 2025-05-26 04:23

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bwf_core', '0003_rename_worflow_type_workflow_workflow_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowversion',
            name='version_number',
            field=models.IntegerField(max_length=15),
        ),
    ]
