# Generated by Django 5.2 on 2025-07-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwf_core', '0004_alter_workflowversion_version_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
